version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: mystos
      POSTGRES_USER: myst
      POSTGRES_PASSWORD: myst
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
