services:
  - type: web
    name: myst-site
    env: node
    plan: starter
    region: virginia
    buildCommand: |
      export PNPM_HOME="$HOME/.local/share/pnpm"
      export PATH="$PNPM_HOME:$PATH"
      export HUSKY=0
      npx -y pnpm@9.15.9 install --frozen-lockfile --prod=false
      # Contentlayer is already invoked by next-contentlayer during build
      # Avoid separate CLI invocation which throws on Node 20 despite success
      npx -y pnpm@9.15.9 --filter site build
    startCommand: |
      set -eux
      export PNPM_HOME="$HOME/.local/share/pnpm"
      mkdir -p "$PNPM_HOME"
      export PATH="$PNPM_HOME:$PATH"
      npx -y pnpm@9.15.9 --filter site start --hostname 0.0.0.0 --port $PORT
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        fromDatabase:
          name: mystos-db
          property: connectionString
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_GA4_ID
        sync: false
      - key: NEXT_PUBLIC_META_PIXEL_ID
        sync: false
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_APPOINTMENT_TIMEZONE
        sync: false
      - key: API_BASE_URL
        sync: false
      - key: ADMIN_API_KEY
        sync: false
    buildFilter:
      paths:
        - apps/site/**
        - packages/**
        - package.json
        - pnpm-lock.yaml
        - turbo.json
  - type: web
    name: myst-api
    env: node
    plan: starter
    region: virginia
    buildCommand: |
      export PNPM_HOME="$HOME/.local/share/pnpm"
      export PATH="$PNPM_HOME:$PATH"
      export HUSKY=0
      npx -y pnpm@9.15.9 install --frozen-lockfile --prod=false
      npx -y pnpm@9.15.9 --filter api build
    startCommand: |
      set -eux
      export PNPM_HOME="$HOME/.local/share/pnpm"
      mkdir -p "$PNPM_HOME"
      export PATH="$PNPM_HOME:$PATH"
      npx -y pnpm@9.15.9 --filter api start --hostname 0.0.0.0 --port $PORT
    preDeployCommand: |
      set -eux
      export PNPM_HOME="$HOME/.local/share/pnpm"
      mkdir -p "$PNPM_HOME"
      export PATH="$PNPM_HOME:$PATH"
      npx -y pnpm@9.15.9 -w db:migrate
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        fromDatabase:
          name: mystos-db
          property: connectionString
      - key: API_BASE_URL
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: APPOINTMENT_TIMEZONE
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_CALENDAR_ID
        sync: false
      - key: GA4_MEASUREMENT_ID
        sync: false
      - key: GA4_API_SECRET
        sync: false
      - key: QUOTE_ALERT_EMAIL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: OUTBOX_BATCH_SIZE
        sync: false
      - key: OUTBOX_POLL_INTERVAL_MS
        sync: false
    buildFilter:
      paths:
        - apps/api/**
        - packages/**
        - drizzle.config.ts
        - package.json
        - pnpm-lock.yaml
        - turbo.json
  - type: redis
    name: myst-redis
    plan: starter
    region: virginia
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all Render services (adjust as needed)
databases:
  - name: mystos-db
    plan: basic-1gb
    region: virginia
    databaseName: mystos
    user: myst
    ipAllowList: []
